[package]
name = "wie_backend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytemuck = { workspace = true }
tracing = { workspace = true }

encoding_rs = { version = "^0.8" }
cfg-if = { version = "^1.0" }
image = { version = "^0.24" }
softbuffer = { version = "^0.3" }
winit = { version = "0.28.0", features = ["wayland"] }
zip = { version = "^0.6", features = ["deflate"], default-features = false }
time = { version = "^0.3" }

wie_base = { path = "../wie_base" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
time = { version = "^0.3", features = ["wasm-bindgen"] }
wasm-bindgen = { version = "^0.2" }
web-sys = { version = "^0.3" }
