[package]
name = "wie_j2me"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytemuck = { workspace = true }
tracing = { workspace = true }

wie_backend = { path = "../wie_backend" }
wie_base = { path = "../wie_base" }
wie_core_jvm = { path = "../wie_core_jvm" }
